import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <h1>Clube Virtual de Ciências</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sed porta est, at ornare lorem. Fusce turpis orci, viverra non ligula sit amet, condimentum condimentum turpis. Mauris ac laoreet odio. Phasellus quis erat nisi. Vestibulum at luctus eros. Fusce sed hendrerit nibh. Duis tempus enim a augue aliquam volutpat. Nam finibus commodo semper. Mauris non egestas erat. Proin in metus nec lacus eleifend hendrerit.
      <p>Aliquam nisi diam, pulvinar sit amet tristique a, rutrum sed nisl. Suspendisse potenti. Maecenas porttitor, turpis ut luctus commodo, ipsum lectus semper libero, nec molestie odio nibh eget felis. Duis ac urna sollicitudin, pulvinar nunc blandit, ultrices nisl. Fusce varius semper ligula ut egestas. Maecenas quis ultrices metus. Aenean sagittis turpis sed quam euismod, vel accumsan dolor bibendum. Sed vel semper est. Curabitur augue mauris, luctus ut orci non, fringilla molestie mauris. Vivamus molestie pulvinar pulvinar. Integer tincidunt blandit quam, id semper elit luctus vitae. Fusce vulputate, lacus vel lacinia malesuada, velit augue dictum urna, ac bibendum dui magna a ex. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam eu blandit velit. Fusce tristique bibendum sapien, ut laoreet enim. Nam faucibus dictum ex id iaculis.</p>
      <p>Nunc ex ex, suscipit eget mollis non, consectetur non elit. Nulla vitae turpis vel massa vestibulum venenatis. Nulla in risus enim. Vestibulum vulputate, metus a semper maximus, est lorem tristique erat, eu pulvinar leo risus nec nulla. Quisque eu risus ut nunc accumsan luctus at vitae enim. Nam gravida dui vel erat malesuada ullamcorper. Aenean maximus aliquet sagittis. Mauris elementum eros sed ex molestie iaculis. Morbi eget quam sed felis tincidunt viverra. Aenean eget turpis eros. Etiam ut dolor vulputate, eleifend justo non, posuere ligula. Cras interdum dolor tellus, pretium accumsan diam suscipit ut. Pellentesque interdum, eros nec ultricies imperdiet, purus metus aliquet tortor, quis euismod nibh erat eget risus.</p>
      <p>Curabitur molestie turpis mauris, eget eleifend erat accumsan vel. Praesent ultricies velit in dolor imperdiet, elementum laoreet lectus faucibus. Morbi tincidunt turpis quis risus ullamcorper dapibus. Sed viverra nisl eu hendrerit feugiat. Sed suscipit auctor lacus, sed rutrum libero tempor et. Duis euismod nibh convallis, aliquam magna eget, auctor ligula. Curabitur dui justo, dictum in urna accumsan, fringilla finibus metus. Nunc pharetra tortor eget massa luctus, eget rhoncus nulla laoreet. Ut dictum commodo consectetur. Cras sit amet lorem ultricies, rutrum augue quis, mollis turpis. Pellentesque a urna ullamcorper augue commodo tempor.</p>
      <p>Donec nec magna fringilla, auctor ex eget, aliquam diam. Integer a viverra eros, nec vulputate eros. Donec diam enim, tristique nec mi eu, pretium luctus est. Fusce lacinia lectus eget risus facilisis ornare. Nulla facilisi. Suspendisse ante magna, molestie quis lorem vitae, convallis vehicula urna. Proin molestie imperdiet ante, eu posuere nulla volutpat pulvinar. Nullam bibendum pellentesque tempus. Vestibulum nibh arcu, dapibus et varius in, dignissim vel magna. Integer vestibulum gravida sapien ut vestibulum.</p>
    </div>
  )
}
